name: Build Release Draft

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark as pre-release'
        type: boolean
        required: false
        default: false
      version:
        description: 'Version (e.g. 0.1.0; leave empty to auto-increment minor from latest release, e.g. 0.1.0 -> 0.2.0)'
        required: false

permissions:
  contents: write

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      prerelease: ${{ inputs.prerelease }}
      version: ${{ inputs.version }}
    secrets: inherit

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download x64
        uses: actions/download-artifact@v4
        with:
          name: Starshot-${{ needs.build.outputs.vl }}-win-x64
          path: x64
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: Starshot-${{ needs.build.outputs.vl }}-win-arm64
          path: arm64

      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.build.outputs.vl }}
          name: ${{ needs.build.outputs.v }}
          body: |
            ### Download / 下载

            - **x64**: [Starshot-${{ needs.build.outputs.vl }}-win-x64.zip](https://github.com/${{ github.repository }}/releases/download/${{ needs.build.outputs.vl }}/Starshot-${{ needs.build.outputs.vl }}-win-x64.zip)
            - **arm64**: [Starshot-${{ needs.build.outputs.vl }}-win-arm64.zip](https://github.com/${{ github.repository }}/releases/download/${{ needs.build.outputs.vl }}/Starshot-${{ needs.build.outputs.vl }}-win-arm64.zip)

            ---

          draft: true
          prerelease: ${{ inputs.prerelease }}
          files: |
            x64/Starshot-${{ needs.build.outputs.vl }}-win-x64.zip
            arm64/Starshot-${{ needs.build.outputs.vl }}-win-arm64.zip
            x64/diff-*-win-x64.zip
            arm64/diff-*-win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
